### ISSUE TITLE
Where is native library?

### ISSUE THREAD

**Issue by willowTank** [bieliaievays/Tess-two_example#4]
I want to get native libaray

**Comment by ashomokdev** [comment]
Hi. Tesseract is native library.

11 Сен 2017 г. 12:50 PM пользователь "willowTank" <notifications@github.com>
написал:

**Comment by willowTank** [comment]
Thanks for your reply but I cann't find JNI code part in project.

**Comment by willowTank** [comment]
Thanks for your reply but I cann't find JNI code part in project.

**Comment by ashomokdev** [comment]
This is because I use Grade. I don't add this library manually. Grade do it
for me.

I use Tess-two library using Grade. The Tess-two library uses Tesseract
inside it.

So I don't use Tesseract directly.


11 Сен 2017 г. 1:02 PM пользователь "willowTank" <notifications@github.com>
написал:
